CREATE TABLE IF NOT EXISTS manga (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    dex_id VARCHAR(255) UNIQUE,
    author VARCHAR(255),
    release_year INT,
    status VARCHAR(50),
    rating DOUBLE PRECISION,
    description TEXT,
    cover_url VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS manga_genres (
    manga_id BIGINT NOT NULL,
    genre VARCHAR(100) NOT NULL,
    CONSTRAINT fk_manga FOREIGN KEY (manga_id)
        REFERENCES manga (id) ON DELETE CASCADE
);